### ISSUE TITLE
Error with trailing comma

### ISSUE THREAD

**Issue by arielger** [benrei/env-path#3]
I'm getting the following error when running `env-path` inside a CI environment with node v6.14.4.

```
root@f0c0854ffbae:/src# ./node_modules/.bin/env-path -p ./.env.development ./node_modules/.bin/react-scripts build
/src/node_modules/env-path/lib/main.js:25
);
^
SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/src/node_modules/env-path/bin/env-path:3:1)
```

It looks related to this line of code:
https://github.com/benrei/env-path/blob/master/lib/main.js#L24

Seems that trailing commas in function arguments are only accepted from node v8 while this package should support node from version 6.9.0 (based on the engines key in package.json).

Thanks for all your work in this package, it was really helpful 😁

**Comment by benrei** [comment]
Thanks for reporting!
As you say [trailing-commas-in-function-syntax](https://node.green/#ES2017-features-trailing-commas-in-function-syntax) is not allowed before node v8.
I will push a fix right away.
